-- Creating the tables
CREATE TABLE IF NOT EXISTS Admins(
    Id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    Email VARCHAR(150), 
    Password VARCHAR(150), 
    LastName VARCHAR(150),
    FirstName VARCHAR(150),
    Gender VARCHAR(150),
    BirthDate DATE,
    PhysicalAddress VARCHAR(150),
    Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Contributors(
    Id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SuggestionId INT(10) NOT NULL,
    ContribId INT(10) NOT NULL,
    Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Events(
    Id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BenefId INT(10) NOT NULL,
    ContribId INT(10) NOT NULL,
    Topic VARCHAR(1000),
    EventDescription VARCHAR(1000),
    EventInfo VARCHAR(1000),
    StartTime DATE,
    EndTime DATE,
    Status VARCHAR(1000),
    Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FeedbackMessages(
    Id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    Email VARCHAR(1000),
    Message VARCHAR(1000), 
    Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Financials(
    Id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BenefId INT(10) NOT NULL,
    ContribId INT(10) NOT NULL,
    Amount INT(10) NOT NULL,
    Currency VARCHAR(1000),
    FinancialInfo VARCHAR(1000),
    FinancialDescription VARCHAR(1000),
    Status VARCHAR(1000),
    Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Messages(
    Id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SenderId INT(10) NOT NULL,
    SenderType VARCHAR(1000),
    Sender VARCHAR(1000),
    ReceiverId INT(10) NOT NULL,
    ReceiverType VARCHAR(1000),
    Receiver VARCHAR(1000),
    Message VARCHAR(1000),
    Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Opportunities(
    Id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BenefId INT(10) NOT NULL,
    ContribId INT(10) NOT NULL,
    Type VARCHAR(1000),
    Description VARCHAR(1000),
    Requirements VARCHAR(1000),
    Status VARCHAR(1000),
    Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Suggestions(
    Id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BenefId INT(10) NOT NULL,
    Title VARCHAR(1000), 
    Description VARCHAR(1000),
    Type VARCHAR(1000),
    StartTime DATE,
    EndTime DATE,
    Info VARCHAR(1000),
    Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Users(
    Id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR(1000),
    LastName VARCHAR(1000),
    Email VARCHAR(1000),
    Type VARCHAR(1000),
    Password VARCHAR(1000),
    ProfilePicture VARCHAR(1000),
    Resume VARCHAR(1000),
    BirthDate DATE,
    PhysicalLocation VARCHAR(1000),
    PhoneNo VARCHAR(1000),
    FinancialDetails VARCHAR(1000)
);

ALTER TABLE Contributors ADD FOREIGN KEY (SuggestionId) REFERENCES Suggestions(Id);
ALTER TABLE Contributors ADD FOREIGN KEY (ContribId) REFERENCES Users(Id);

ALTER TABLE Events ADD FOREIGN KEY (BenefId) REFERENCES Users(Id);
ALTER TABLE Events ADD FOREIGN KEY (ContribId) REFERENCES Users(Id);

ALTER TABLE Financials ADD FOREIGN KEY (BenefId) REFERENCES Users(Id);
ALTER TABLE Financials ADD FOREIGN KEY (ContribId) REFERENCES Users(Id);

ALTER TABLE Messages ADD FOREIGN KEY (SenderId) REFERENCES Users(Id);
ALTER TABLE Messages ADD FOREIGN KEY (ReceiverId) REFERENCES Users(Id);

ALTER TABLE Opportunities ADD FOREIGN KEY (BenefId) REFERENCES Users(Id);
ALTER TABLE Opportunities ADD FOREIGN KEY (ContribId) REFERENCES Users(Id);

ALTER TABLE Suggestions ADD FOREIGN KEY (BenefId) REFERENCES Users(Id);